# docker-build-dev:
#   stage: docker-deploy-client-environment
#   extends:
#     - .image-docker-with-bash
#   rules:
#     - if: '$CI_COMMIT_BRANCH != "u202001-dev"'
#       when: never
#     - if: '$CI_COMMIT_MESSAGE !~ /(\[app\])/'
#       when: never
#     - when: always
#   script:
#     - cd $APP_PATH
#     - "bash deploy_enviroment_client.ci -a $MODULE_NAME -c $CI_COMMIT_BRANCH -imageSuffix .client -d $CI_COMMIT_DESCRIPTION_SIMPLE"
#     - "curl $WEBHOOK_URL_APP_DEV"
          
docker-build-test:
  stage: docker-deploy-client-environment
  extends:
    - .image-docker-with-bash
  rules:
    - if: '$CI_COMMIT_BRANCH != "test"'
      when: never
    - if: '$CI_COMMIT_MESSAGE !~ /(\[app\])/'
      when: never
    - when: always
  script:
    - cd $APP_PATH
    - git config --global http.sslVerify false
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.dttt.vn/gitadmin/gitlabutils
    - cd gitlabutils/gitlab-environment
    - "bash deploy_enviroment_client.ci -a $MODULE_NAME -c $CI_COMMIT_BRANCH -imageSuffix .client -s $CI_COMMIT_DESCRIPTION_SIMPLE -d $TARGET_ENVIRONMENT_DEPLOY"
    - cd ..
    - WEBHOOK_URL_APP=$(echo "WEBHOOK_URL_APP_TEST"_"$TARGET_ENVIRONMENT_DEPLOY")
    - echo ${!WEBHOOK_URL_APP}
    - "curl -X POST $(echo ${!WEBHOOK_URL_APP})"

docker-build-stagging:
  stage: docker-deploy-client-environment
  extends:
    - .image-docker-with-bash
  rules:
    - if: '$CI_COMMIT_BRANCH != "stagging"'
      when: never
    - if: '$CI_COMMIT_MESSAGE !~ /(\[app\])/'
      when: never
    - when: always
  script:
    - cd $APP_PATH
    - git config --global http.sslVerify false
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.dttt.vn/gitadmin/gitlabutils
    - cd gitlabutils/gitlab-environment
    - "bash deploy_enviroment_client.ci -a $MODULE_NAME -c $CI_COMMIT_BRANCH -imageSuffix .client -s $CI_COMMIT_DESCRIPTION_SIMPLE -d $TARGET_ENVIRONMENT_DEPLOY"
    - cd ..
    - WEBHOOK_URL_APP=$(echo "WEBHOOK_URL_APP_STAGGING"_"$TARGET_ENVIRONMENT_DEPLOY")
    - echo ${!WEBHOOK_URL_APP}
    - "curl -X POST $(echo ${!WEBHOOK_URL_APP})"

docker-build-production:
  stage: docker-deploy-client-environment
  extends:
    - .image-docker-with-bash
  rules:
    - if: '$CI_COMMIT_BRANCH != "prod"'
      when: never
    - if: '$CI_COMMIT_MESSAGE !~ /(\[app\])/'
      when: never
    - when: always
  script:
    - cd $APP_PATH
    - git config --global http.sslVerify false
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.dttt.vn/gitadmin/gitlabutils
    - cd gitlabutils/gitlab-environment
    - "bash deploy_enviroment_client.ci -a $MODULE_NAME -c $CI_COMMIT_BRANCH -imageSuffix .client -s $CI_COMMIT_DESCRIPTION_SIMPLE -d $TARGET_ENVIRONMENT_DEPLOY"
    - cd ..
    - WEBHOOK_URL_APP=$(echo "WEBHOOK_URL_APP_PROD"_"$TARGET_ENVIRONMENT_DEPLOY")
    - echo ${!WEBHOOK_URL_APP}
    - "curl -X POST $(echo ${!WEBHOOK_URL_APP})"
